### ISSUE TITLE
Update dev2/demo

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/pipelines#10]

**Comment by ineagu** [comment]
ai incercat ceva aiic ?

**Comment by rodica-andronache** [comment]
da, am facut update pe dev si le luam pe toate la rand sa vad daca au probleme. Nu asta trebuia sa fac?

**Comment by ineagu** [comment]
ba da, vroiam sa vad un status :D

**Comment by rodica-andronache** [comment]
am testat pe dev2. Ce am gasit:
- la flymag - nu a mes sa fac update . a zis marius ca o sa puna el scriptul nou de update sau cam asa ceva
- la flymag si amadeus nu a mers sa activez WP Product Reviews care e recomandat in tema . Imi aparea "Something went wrong with the plugin API." 
Pot sa ma apuc de demo? Ca nu sunt sincronizate dev2/demo asa ca nu prea se poate testa tot pe dev2

**Comment by ineagu** [comment]
ar trebui sa importe marius toate bazele de date de pe demo pe dev2

ar trebui sa facem asta din cand in cand.

On Tue, May 10, 2016 at 3:52 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> am testat pe dev2. Ce am gasit:
>
>    - la flymag - nu a mes sa fac update . a zis marius ca o sa puna el
>    scriptul nou de update sau cam asa ceva
>    - la flymag si amadeus nu a mers sa activez WP Product Reviews care e
>    recomandat in tema . Imi aparea "Something went wrong with the plugin API."
>    Pot sa ma apuc de demo? Ca nu sunt sincronizate dev2/demo asa ca nu prea se
>    poate testa tot pe dev2
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/pipelines/issues/10#issuecomment-218163560>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
o sa-i spun. Pana atunci ma apuc de demo-uri? ca nu ai zis :)

**Comment by ineagu** [comment]
dap poti face asta, daca nu e prea tarziu

**Comment by rodica-andronache** [comment]
da, mai bine fac maine in caz ca apar probleme sa am mai mult timp :)

**Comment by rodica-andronache** [comment]
@ineagu am facut update si pe demo si am verificat.
- La flymag e o eroare de js in consola pt ca nu pot sa fac update inca la tema. O sa vb cu mariusc de asta
- aici http://demo.themeisle.com/zerif-origin/ s-au stricat alinierea widget-urilor alea dar nu stiu daca acum sau era asa dinainte de update . Si nu stiu nici daca o sa-l mai folosim, adica daca se merita sau nu sa ma uit ce s-a intamplat
- la llorix one plus imaginile de la latest news apar un pic taiate, dar cred ca poate fi ceva din plugin trebuie sa ma uit

**Comment by ineagu** [comment]
aici : http://demo.themeisle.com/zerif-origin/ ar trebui verificat si
reparat, probabil o sa il folosim, si daca ni sa stricat noua o sa se
strice si clientilor :))

sa te uiti la llorix one plus :D

2016-05-11 16:08 GMT+02:00 Rodica-Elena Andronache <notifications@github.com
>:

> @ineagu <https://github.com/ineagu> am facut update si pe demo si am
> verificat.
>
>    - La flymag e o eroare de js in consola pt ca nu pot sa fac update
>    inca la tema. O sa vb cu mariusc de asta
>    - aici http://demo.themeisle.com/zerif-origin/ s-au stricat alinierea
>    widget-urilor alea dar nu stiu daca acum sau era asa dinainte de update .
>    Si nu stiu nici daca o sa-l mai folosim, adica daca se merita sau nu sa ma
>    uit ce s-a intamplat
>    - la llorix one plus imaginile de la latest news apar un pic taiate,
>    dar cred ca poate fi ceva din plugin trebuie sa ma uit
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/pipelines/issues/10#issuecomment-218470345>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
@mileamadalin aici am mai refacut eu putin http://demo.themeisle.com/zerif-origin/ dar poti sa-mi spui exact cum era inainte?

**Comment by mileamadalin** [comment]
@rodica-andronache cam asa http://berlin-trails.com 

Este mult css pe acolo, daca e ma pot ocupa eu.

**Comment by rodica-andronache** [comment]
@mileamadalin da, te poti ocupa si daca ai nevoie de ajut imi spui

**Comment by rodica-andronache** [comment]
@mileamadalin  sa nu uiti de asta te rog.

**Comment by rodica-andronache** [comment]
@mileamadalin un update te rog :)

**Comment by mileamadalin** [comment]
@rodica-andronache Pe asta il fac saptamana viitoare.
