### ISSUE TITLE
Check Rhea theme

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/pipelines#12]

**Comment by rodica-andronache** [comment]
@ineagu m-am uitat pe tema. Mie una nu mi se pare prea tare.

Imi place schema de culori si partea de design cu meniul.
Ca si implementare, nu e neaparat cea mai buna, avand in vedere ca zerif in sine, nu prea are hook-uri si filtre, si e greu de facut child theme cu ea, asa ca ar avea nevoie de schimbari, cand se actualizeaza zerif + modificari ca sa mearga cu pro
daca iti place designul, putem sa ne inspiram din el si sa facem noi un child theme (inainte sa facem zerif mai child friendly), poate ar fi mai eficient, decat sa modificam la asta. Nu stiu nici eu cum e mai bine

**Comment by ineagu** [comment]
Ok, mai putem pune filtre si sa ii zicem sa mai aranjeze pe la el si sa il faca pro-compatible nu? Oricum a zis ca nu e terminat. Nu vreau sa lucram noi la asta.

Imi lasi o lista cu ce imbunatatiri mai tre sa faca ok ?

**Comment by rodica-andronache** [comment]
- sa verifice de Warning-uri/notificari: http://prntscr.com/c0smre
- screenshot
- nu cred ca e bine sa dea remove la sectiuni, cum ar fi cea de parallax sau ribbon. Poate doar sa le ascunda default (la care e cazul) dar sa existe posibilitatea sa le foloseasca - asta mi s-a parut mie ca ii deranja pe oamenii cu child theme
- si zerif lite si mai ales pro au hook-uri si filtre, si sigur unele parti din tema pot fi facute, fara a mai suprascrie fisierele din sections sau chiar footer.php. 
- Pentru sectiunea de Our focus de ex, au fost inregistrate niste widget-uri noi rhea_features_block, care nici nu functioneaza in totalitate (doar textul din interior pare sa se modifice) . Mie nu mi se pare ca are rost atata cod rescris, care poate sa incurce pe viitor, doar pentru a schimba textul de aici http://prntscr.com/c0sznh . Mai bine adaugam noi niste filtre in zerif daca e necesar.
- Sunt probleme la Latest news, cand posturile au poze pare http://prntscr.com/c0st4e
- Probleme pe mobil cu meniul
- De adaugat un fisier readme.txt cu licente/resurse
- Paginile interne(page, single, search, archive etc) au probleme cu header-ul http://prntscr.com/c0sweo
- fisierul testimonials.php pare identic ca si in zerif, nu imi dau seama de ce a fost suprascris. In principiu, nu ar trebui suprascrise fiserele decat daca nu se poate face din css/hook-uri sau filtre
- adaugat text domain si folder languages cu fisierul .pot in el
- verificat cu Theme check plugin
- Sectiunile astea din footer apar doar in customize, pe site nu (eu nu le-as scoate nici din customize, poate sa fie default ascunse, dar sa poata fi puse din motivul pe care l-am spus mai sus)
- compatibilitate cu zerif pro (toate sectiunile din pro ar trebui sa functioneze, packages, background slider/background video etc)

@ineagu daca trebuie sa scriu in engleza, sau altceva sa-mi zici

**Comment by ineagu** [comment]
please close this and any other finished task.
