### ISSUE TITLE
Visuals for August newsletter

### ISSUE THREAD

**Issue by s2abina** [Codeinwp/pipelines#16]
-Easy Content Types new UX - screenshot 590x380px
-ReviveSocial image 550x420
-TheMotion image 550x420 

 We might need a couple more, will come back with details

**Comment by s2abina** [comment]
@abaicus I can show you the newsletter template so it makes more sense.

Weneed to send this tomorrow :/

**Comment by abaicus** [comment]
![nletter](https://cloud.githubusercontent.com/assets/15010186/17367040/e9224568-5996-11e6-83d7-e9a99b9a59dc.jpg)
![revive_social](https://cloud.githubusercontent.com/assets/15010186/17367037/e8d7e608-5996-11e6-8b83-f29be0fe3094.png)
![themotion_logo](https://cloud.githubusercontent.com/assets/15010186/17367038/e8f89704-5996-11e6-81af-5dc445e77f94.png)
![ecpt_interface](https://cloud.githubusercontent.com/assets/15010186/17367039/e90198c2-5996-11e6-89ef-21d3f869972f.png)

**Comment by s2abina** [comment]
Thanks, great! I will close this.
