### ISSUE TITLE
add subject as theme tag

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/pipelines#17]
@mileamadalin please go over our top10 themes on w.org and add required tags from here in style.css : https://www.dropbox.com/s/901h1rqtw7ypeow/Screenshot%202016-08-14%2016.07.38.png?dl=0

cc @rodica-andronache

**Comment by rodica-andronache** [comment]
we should also remove the deprecated tags too, so please check all the themes with Theme check

**Comment by ineagu** [comment]
updates ?

**Comment by mileamadalin** [comment]
@ineagu I will do that today

**Comment by ineagu** [comment]
any idea why is this in progress after 1 month ?

**Comment by mileamadalin** [comment]
Stiu ca le facusem, dar am uitat sa inchid. mai verific o data astazi sa vad daca am omis ceva.
