### ISSUE TITLE
Add all repos

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/pipelines#2]
@rodica-andronache I did some repetitive work in order to merge some of the repos, we will need to merge all of them in this board.

**Comment by rodica-andronache** [comment]
@ineagu can we delete some of this repos ?:

this are tests:
https://github.com/Codeinwp/test-theme-repository
https://github.com/Codeinwp/test-plugin
https://github.com/Codeinwp/test-repository

this are from ready themes:
https://github.com/Codeinwp/SimplyClean1/
https://github.com/Codeinwp/Sniper-Theme/
https://github.com/Codeinwp/readylinks/
https://github.com/Codeinwp/AffiliateTheme
https://github.com/Codeinwp/SimpleReviews

https://github.com/Codeinwp/litchi

**Comment by ineagu** [comment]
yes, we can

On Mon, Apr 4, 2016 at 6:18 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> can we delete some of this repos ?:
>
> this are tests:
> https://github.com/Codeinwp/test-theme-repository
> https://github.com/Codeinwp/test-plugin
> https://github.com/Codeinwp/test-repository
>
> this are from ready themes:
> https://github.com/Codeinwp/SimplyClean1/
> https://github.com/Codeinwp/Sniper-Theme/
> https://github.com/Codeinwp/readylinks/
> https://github.com/Codeinwp/AffiliateTheme
> https://github.com/Codeinwp/SimpleReviews
>
> https://github.com/Codeinwp/litchi
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/pipelines/issues/2#issuecomment-205344487>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
