### ISSUE TITLE
Improve themeisle page on TF

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/pipelines#20]
@abaicus @rodica-andronache  using the current site design and getting inspired by this : https://themeforest.net/user/pixelgrade, we should be able to improve : https://themeforest.net/user/themeisle

We need : team + testimonials + trust signs  ( creators of Zerif, used by 400k people and featured in forbes, smashing etc etc )

**Comment by ineagu** [comment]
@pbworksro asta e tot cam din aceeasi poveste cu LP de la themotion 🗡

**Comment by UVLabs** [comment]
October is spelt wrong in the graphic https://themeforest.net/item/themotion-video-blogging-wordpress-theme/17381393

**Comment by ineagu** [comment]
@pbworksro I think using the same logic from the landing page we should redesign this https://themeforest.net/user/themeisle. Can we try it next week ? Some elements should be already there, @karol can help a bit with the copy I think .

**Comment by rodica-andronache** [comment]
@bogdanpopa90 how is this going? Do you need help with something? :D

**Comment by bogdanpopa90** [comment]
@ineagu What do you think about these changes on Envato profile?
Also let me know what additional info you want to add in content area (where is now Creators of...)

![Uploading screenshot-1.jpg…]()

**Comment by bogdanpopa90** [comment]
![screenshot-1](https://cloud.githubusercontent.com/assets/23031578/21103168/fc445f0a-c089-11e6-92f9-3efa9f8b9276.jpg)

**Comment by bogdanpopa90** [comment]
@rodica-andronache Envato profile was updated
