### ISSUE TITLE
Check Rise Lite child theme with Zerif PRO

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/pipelines#8]
https://wordpress.org/themes/rise-lite/

**Comment by rodica-andronache** [comment]
Testimoniale: http://prnt.sc/b1zuhp
Ribbon: http://prntscr.com/b1zuof
Header in customizer: http://prntscr.com/b1zuyo
Our focus section in customizer: http://prntscr.com/b1zv6a
Ribbon in customizer: http://prntscr.com/b1zvcn
In customizer, cam toate sectiunile arata altfel default, decat pe site
Hide big title nu functioneaza pe site
Culorile pt butoane din big title nu functioneaza
In principiu mai multe elemente din big title, about us si ribbon-uri nu functioneaza pt ca sectiunile sunt suprascrise in child theme
Background slider/video nu functioneaza.

@ineagu aici ce ar trebui sa fac? nu am gasit undeva pe git sa le trimit un pull . Sau rezolva ei?

**Comment by ineagu** [comment]
se ocupa ei

2016-05-09 15:23 GMT+02:00 Rodica-Elena Andronache <notifications@github.com
>:

> Testimoniale: http://prnt.sc/b1zuhp
> Ribbon: http://prntscr.com/b1zuof
> Header in customizer: http://prntscr.com/b1zuyo
> Our focus section in customizer: http://prntscr.com/b1zv6a
> Ribbon in customizer: http://prntscr.com/b1zvcn
> In customizer, cam toate sectiunile arata altfel default, decat pe site
> Hide big title nu functioneaza pe site
> Culorile pt butoane din big title nu functioneaza
> In principiu mai multe elemente din big title, about us si ribbon-uri nu
> functioneaza pt ca sectiunile sunt suprascrise in child theme
> Background slider/video nu functioneaza.
>
> @ineagu <https://github.com/ineagu> aici ce ar trebui sa fac? nu am gasit
> undeva pe git sa le trimit un pull . Sau rezolva ei?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/pipelines/issues/8#issuecomment-217862587>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
@ineagu  ok, deci inchid aici?

**Comment by ineagu** [comment]
dap

On Mon, May 9, 2016 at 3:29 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> ok, deci inchid aici?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/pipelines/issues/8#issuecomment-217864004>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
